### ISSUE TITLE
Linting errors triggered by components starting with "style" or "script"

### ISSUE THREAD

**Issue by charlescurrier** [UnwrittenFun/svelte-language-server#21]
Any tags starting with the word "style" or "script" regardless of capitalization pollutes the editor with invalid linting errors. Only code within the actual `<style>`  and `<script>` tags should be linted.

**Comment by UnwrittenFun** [comment]
Can't reproduce this, perhaps it was fixed along the way?

**Comment by DamOrtTearlach** [comment]
Still seeing the issue. To reproduce you will need to create a component who's name starts with "style" or "script". Then import that component, and use it in your markup.
<img width="703" alt="Screen Shot 2019-10-07 at 9 44 07 AM" src="https://user-images.githubusercontent.com/13203501/66322062-2a859e00-e8e7-11e9-8ed2-052931037448.png">
